### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by maiststudent** [ytorbyk/magento2-geo-ip2#3]
Looks like the user guide is not currently accessible (http://wiki.to-bai.com/display/TOB/GeoIP%2BUser%2BGuide).

Could you please provide it or include it within the repo?

I'm trying to figure out how to use the paid/licensed dBs.

Thank you,

**Comment by ytorbyk** [comment]
Hi @maiststudent ,
I understand that it's a little late, the user guid is added.
