### ISSUE TITLE
Got the error after installing th extension

### ISSUE THREAD

**Issue by malikabid** [ytorbyk/magento2-geo-ip2#8]
Fatal error: Uncaught Error: Class 'GeoIp2\Database\Reader' not found in /var/www/html/rmlive/app/code/Tobai/GeoIp2/Model/Database/ReaderFactory.php on line 43

**Comment by malikabid** [comment]
Installing it properly using composer - fixed the issue.

**Comment by balusai** [comment]
Hi @malikabid Could you please explain how it works, installed via composer both [ composer require tobai/magento2-geo-ip2 and   composer require tobai/magento2-geo-store-switcher] . And created 3 store views for main webstore. configured japan store view for Country India, but when i click on url from indian ip addresses, it is in default store view only , it is not redirected to japan store view. Could you please help me what i missed.
